name: core
description: "A new Flutter project."
version: 0.0.1

publish_to: 'none'

environment:
  sdk: '>=3.4.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^4.0.0
  shared:
    path: ../shared
  intl: any
  shared_preferences: any
  provider: any
  freezer: any
  json5_model: any
  json_annotation: any
  flutter_svg: any
  json_serializable: any
  build_runner: any
  flutter_gen: any
  freezed_annotation: any
  bloc: any
  flutter_gen_runner: any
  dio: any
  jwt_decoder: any
  path: any
  equatable: any
  flutter_bloc: any



freezed:
  options:
    # Tells Freezed not to format .freezed.dart files.
    # This can significantly speed up code-generation.
    format: true
    # Disable the generation of copyWith/== for the entire project
    copy_with: true
    equal: true
    # `when` and `map` can be enabled/disabled entirely by setting them to `true`/`false`
    map: false
    # We can also enable/disable specific variants of `when`/`map` by setting them to `true`/`false`:
    when:
      when: true
      maybe_when: true
      when_or_null: false


flutter_gen:
  enabled: true
  output: lib/assetsGen/
  integrations:
    flutter_svg: true
  assets:
    prefix: asset_
    outputs:
      class_name: MockAssets

#  flutter_intl: any
#  webview_flutter: ^4.8.0

#  flutter_svg_icons: ^0.0.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: any

analyzer:
  errors:
    invalid_annotation_target: ignore


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/json/
    - assets/images/


#  assets:
#    - assets/effect.svg
#    - assets/notEffect.svg
  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
